name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: make setup
    - name: testing
      run: make test
    - name: linting
      run: make lint
